# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabwidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(623, 531)
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(50, 60, 521, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        TabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 621, 491))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        TabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        TabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        TabWidget.addTab(self.tab_4, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("TabWidget", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("TabWidget", "2131"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("TabWidget", "1231"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("TabWidget", "3123"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("TabWidget", "2342"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TabWidget", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TabWidget", "1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TabWidget", "2"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TabWidget", "3"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TabWidget", "5"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "策略运行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("TabWidget", "用户日志"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("TabWidget", "信号记录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("TabWidget", "系统日志"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "运行日志"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_3), _translate("TabWidget", "错误信息"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_4), _translate("TabWidget", "组合监控"))
